sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
#  - clang


before_install:
  - sudo apt-get update
  - sudo apt-get install libmicrohttpd-dev
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - EXT_MICROHTTPD_INC_DIR=/usr/include
  - export EXT_MICROHTTPD_INC_DIR
  - EXT_MICROHTTPD_LIB_DIR=/usr/lib/x86_64-linux-gnu/
  - export EXT_MICROHTTPD_LIB_DIR
  - MY_LOCATION=`pwd`
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - cd quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*
  - mkdir build
  - cd build

script:
  - generate_makefile EXT_microhttpd
  - make test
  - ./bin/EXT_microhttpd.exe
#EOF
