matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx

language: cpp

before_install:
# Microhttpd specific part
#-----------------------
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install libmicrohttpd; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; sudo apt-get install -y libmicrohttpd-dev; fi
# End of Microhttpd specific part
#-----------------------
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - EXT_MICROHTTPD_INC_DIR=/usr/include
  - export EXT_MICROHTTPD_INC_DIR
  - EXT_MICROHTTPD_LIB_DIR=/usr/lib/x86_64-linux-gnu/
  - export EXT_MICROHTTPD_LIB_DIR
  - MY_LOCATION=`pwd`
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - cd quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*
  - mkdir build
  - cd build

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then generate_makefile EXT_microhttpd; make test; ./bin/EXT_microhttpd.exe; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake $QUICKY_REPOSITORY/EXT_microhttpd; make; ./test_EXT_microhttpd; fi
#EOF
